// Generated by CoffeeScript 1.4.0
(function() {
  var Range, exports;

  Range = (function() {

    function Range(start, finish) {
      this.start = start;
      this.finish = finish;
    }

    return Range;

  })();

  exports = module.exports = Range;

}).call(this);
