// Generated by CoffeeScript 1.4.0
(function() {
  var Default, Dot, OrderClauses, ToSql, Visitors, WhereSql, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dot = require('./visitors/dot');

  Default = require('./visitors/default');

  ToSql = require('./visitors/to-sql');

  Visitors = {
    Dot: Dot,
    visitor: function() {
      return new Default();
    },
    JoinSql: {
      visitRelNodesSelectCore: function(o) {
        var _this = this;
        return (o.source.right.map(function(j) {
          return _this.visit(j);
        })).join(' ');
      }
    },
    OrderClauses: OrderClauses = (function(_super) {

      __extends(OrderClauses, _super);

      function OrderClauses() {
        return OrderClauses.__super__.constructor.apply(this, arguments);
      }

      OrderClauses.prototype.visitRelNodesSelectStatement = function(o) {
        var _this = this;
        return o.orders.map(function(x) {
          return _this.visit(x);
        });
      };

      return OrderClauses;

    })(ToSql),
    WhereSql: WhereSql = (function(_super) {

      __extends(WhereSql, _super);

      function WhereSql() {
        return WhereSql.__super__.constructor.apply(this, arguments);
      }

      WhereSql.prototype.visitRelNodesSelectCore = function(o) {
        var _this = this;
        return "WHERE " + ((o.wheres.map(function(x) {
          return _this.visit(x);
        })).join(' AND '));
      };

      return WhereSql;

    })(ToSql)
  };

  exports = module.exports = Visitors;

}).call(this);
