// Generated by CoffeeScript 1.4.0
(function() {
  var Binary, Node, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Node = require('./node');

  Binary = (function(_super) {

    __extends(Binary, _super);

    function Binary(left, right) {
      this.left = left;
      this.right = right;
    }

    return Binary;

  })(Node);

  exports = module.exports = Binary;

}).call(this);
