// Generated by CoffeeScript 1.4.0
(function() {
  var Expressions, FunctionNode, Node, SqlLiteral, exports, u,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  u = require('underscore');

  Node = require('./node');

  SqlLiteral = require('./sql-literal');

  Expressions = require('../expressions');

  FunctionNode = (function(_super) {

    __extends(FunctionNode, _super);

    function FunctionNode(expr, aliaz) {
      if (aliaz == null) {
        aliaz = null;
      }
      this.expressions = expr;
      this.alias = aliaz;
      this.distinct = false;
      u(this).extend(Expressions);
    }

    FunctionNode.prototype.as = function(aliaz) {
      this.alias = new SqlLiteral(aliaz);
      return this;
    };

    return FunctionNode;

  })(Node);

  exports = module.exports = FunctionNode;

}).call(this);
