// Generated by CoffeeScript 1.4.0
(function() {
  var Node, Visitors, exports;

  Visitors = require('../visitors');

  Node = (function() {

    function Node() {}

    Node.prototype.nodes = function() {
      return require('./nodes');
    };

    Node.prototype.not = function() {
      var Not;
      Not = this.nodes.Not;
      return new Not(this);
    };

    Node.prototype.or = function(right) {
      var Grouping, Or;
      Grouping = this.nodes().Grouping;
      Or = this.nodes().Or;
      return new Grouping(new Or(this, right));
    };

    Node.prototype.and = function(right) {
      var And;
      And = this.nodes().And;
      return new And([this, right]);
    };

    Node.prototype.toSql = function() {
      return Visitors.visitor().accept(this);
    };

    return Node;

  })();

  exports = module.exports = Node;

}).call(this);
