// Generated by CoffeeScript 1.4.0
(function() {
  var And, As, Assignment, Attribute, Avg, Between, Bin, Binary, DoesNotMatch, Equality, Except, Exists, FunctionNode, GreaterThan, GreaterThanOrEqual, Group, Grouping, Having, In, InnerJoin, InsertStatement, Intersect, Join, LessThan, LessThanOrEqual, Limit, Lock, Matches, Max, Min, Nodes, Not, NotEqual, NotIn, Offset, On, Or, OuterJoin, SelectCore, SelectStatement, SqlLiteral, StringJoin, Sum, TableAlias, Top, Unary, Union, UnionAll, UnqualifiedColumn, Values, With, WithRecursive, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Binary = require('./binary');

  SelectStatement = require('./select-statement');

  SqlLiteral = require('./sql-literal');

  SelectCore = require('./select-core');

  Unary = require('./unary');

  TableAlias = require('./table-alias');

  And = require('./and');

  FunctionNode = require('./function-node');

  Attribute = require('../attribute');

  InsertStatement = require('./insert-statement');

  Nodes = {
    SelectStatement: SelectStatement,
    InsertStatement: InsertStatement,
    SqlLiteral: SqlLiteral,
    SelectCore: SelectCore,
    Binary: Binary,
    TableAlias: TableAlias,
    And: And,
    Join: Join = (function(_super) {

      __extends(Join, _super);

      function Join() {
        return Join.__super__.constructor.apply(this, arguments);
      }

      return Join;

    })(Binary),
    InnerJoin: InnerJoin = (function(_super) {

      __extends(InnerJoin, _super);

      function InnerJoin() {
        return InnerJoin.__super__.constructor.apply(this, arguments);
      }

      return InnerJoin;

    })(Join),
    OuterJoin: OuterJoin = (function(_super) {

      __extends(OuterJoin, _super);

      function OuterJoin() {
        return OuterJoin.__super__.constructor.apply(this, arguments);
      }

      return OuterJoin;

    })(Join),
    StringJoin: StringJoin = (function(_super) {

      __extends(StringJoin, _super);

      function StringJoin(left, right) {
        if (right == null) {
          right = null;
        }
        StringJoin.__super__.constructor.call(this, left, right);
      }

      return StringJoin;

    })(Join),
    TableAlias: TableAlias = (function(_super) {

      __extends(TableAlias, _super);

      function TableAlias(left, right) {
        this.left = left;
        this.right = right;
        TableAlias.__super__.constructor.call(this, this.left, this.right);
        this.name = this.right;
        this.relation = this.left;
        this.tableAlias = this.name;
        this.tableName = this.relation.name;
      }

      TableAlias.prototype.column = function(name) {
        return new Attribute(this, name);
      };

      return TableAlias;

    })(Binary),
    FunctionNode: FunctionNode,
    Sum: Sum = (function(_super) {

      __extends(Sum, _super);

      function Sum() {
        return Sum.__super__.constructor.apply(this, arguments);
      }

      return Sum;

    })(FunctionNode),
    Exists: Exists = (function(_super) {

      __extends(Exists, _super);

      function Exists() {
        return Exists.__super__.constructor.apply(this, arguments);
      }

      return Exists;

    })(FunctionNode),
    Max: Max = (function(_super) {

      __extends(Max, _super);

      function Max() {
        return Max.__super__.constructor.apply(this, arguments);
      }

      return Max;

    })(FunctionNode),
    Min: Min = (function(_super) {

      __extends(Min, _super);

      function Min() {
        return Min.__super__.constructor.apply(this, arguments);
      }

      return Min;

    })(FunctionNode),
    Avg: Avg = (function(_super) {

      __extends(Avg, _super);

      function Avg() {
        return Avg.__super__.constructor.apply(this, arguments);
      }

      return Avg;

    })(FunctionNode),
    As: As = (function(_super) {

      __extends(As, _super);

      function As() {
        return As.__super__.constructor.apply(this, arguments);
      }

      return As;

    })(Binary),
    Assignment: Assignment = (function(_super) {

      __extends(Assignment, _super);

      function Assignment() {
        return Assignment.__super__.constructor.apply(this, arguments);
      }

      return Assignment;

    })(Binary),
    Between: Between = (function(_super) {

      __extends(Between, _super);

      function Between() {
        return Between.__super__.constructor.apply(this, arguments);
      }

      return Between;

    })(Binary),
    DoesNotMatch: DoesNotMatch = (function(_super) {

      __extends(DoesNotMatch, _super);

      function DoesNotMatch() {
        return DoesNotMatch.__super__.constructor.apply(this, arguments);
      }

      return DoesNotMatch;

    })(Binary),
    GreaterThan: GreaterThan = (function(_super) {

      __extends(GreaterThan, _super);

      function GreaterThan() {
        return GreaterThan.__super__.constructor.apply(this, arguments);
      }

      return GreaterThan;

    })(Binary),
    GreaterThanOrEqual: GreaterThanOrEqual = (function(_super) {

      __extends(GreaterThanOrEqual, _super);

      function GreaterThanOrEqual() {
        return GreaterThanOrEqual.__super__.constructor.apply(this, arguments);
      }

      return GreaterThanOrEqual;

    })(Binary),
    Join: Join = (function(_super) {

      __extends(Join, _super);

      function Join() {
        return Join.__super__.constructor.apply(this, arguments);
      }

      return Join;

    })(Binary),
    LessThan: LessThan = (function(_super) {

      __extends(LessThan, _super);

      function LessThan() {
        return LessThan.__super__.constructor.apply(this, arguments);
      }

      return LessThan;

    })(Binary),
    LessThanOrEqual: LessThanOrEqual = (function(_super) {

      __extends(LessThanOrEqual, _super);

      function LessThanOrEqual() {
        return LessThanOrEqual.__super__.constructor.apply(this, arguments);
      }

      return LessThanOrEqual;

    })(Binary),
    Matches: Matches = (function(_super) {

      __extends(Matches, _super);

      function Matches() {
        return Matches.__super__.constructor.apply(this, arguments);
      }

      return Matches;

    })(Binary),
    NotEqual: NotEqual = (function(_super) {

      __extends(NotEqual, _super);

      function NotEqual() {
        return NotEqual.__super__.constructor.apply(this, arguments);
      }

      return NotEqual;

    })(Binary),
    NotIn: NotIn = (function(_super) {

      __extends(NotIn, _super);

      function NotIn() {
        return NotIn.__super__.constructor.apply(this, arguments);
      }

      return NotIn;

    })(Binary),
    Or: Or = (function(_super) {

      __extends(Or, _super);

      function Or() {
        return Or.__super__.constructor.apply(this, arguments);
      }

      return Or;

    })(Binary),
    Union: Union = (function(_super) {

      __extends(Union, _super);

      function Union() {
        return Union.__super__.constructor.apply(this, arguments);
      }

      return Union;

    })(Binary),
    UnionAll: UnionAll = (function(_super) {

      __extends(UnionAll, _super);

      function UnionAll() {
        return UnionAll.__super__.constructor.apply(this, arguments);
      }

      return UnionAll;

    })(Binary),
    Intersect: Intersect = (function(_super) {

      __extends(Intersect, _super);

      function Intersect() {
        return Intersect.__super__.constructor.apply(this, arguments);
      }

      return Intersect;

    })(Binary),
    Except: Except = (function(_super) {

      __extends(Except, _super);

      function Except() {
        return Except.__super__.constructor.apply(this, arguments);
      }

      return Except;

    })(Binary),
    Bin: Bin = (function(_super) {

      __extends(Bin, _super);

      function Bin() {
        return Bin.__super__.constructor.apply(this, arguments);
      }

      return Bin;

    })(Unary),
    Group: Group = (function(_super) {

      __extends(Group, _super);

      function Group() {
        return Group.__super__.constructor.apply(this, arguments);
      }

      return Group;

    })(Unary),
    Grouping: Grouping = (function(_super) {

      __extends(Grouping, _super);

      function Grouping() {
        return Grouping.__super__.constructor.apply(this, arguments);
      }

      return Grouping;

    })(Unary),
    Having: Having = (function(_super) {

      __extends(Having, _super);

      function Having() {
        return Having.__super__.constructor.apply(this, arguments);
      }

      return Having;

    })(Unary),
    Limit: Limit = (function(_super) {

      __extends(Limit, _super);

      function Limit() {
        return Limit.__super__.constructor.apply(this, arguments);
      }

      return Limit;

    })(Unary),
    Not: Not = (function(_super) {

      __extends(Not, _super);

      function Not() {
        return Not.__super__.constructor.apply(this, arguments);
      }

      return Not;

    })(Unary),
    Offset: Offset = (function(_super) {

      __extends(Offset, _super);

      function Offset() {
        return Offset.__super__.constructor.apply(this, arguments);
      }

      return Offset;

    })(Unary),
    On: On = (function(_super) {

      __extends(On, _super);

      function On() {
        return On.__super__.constructor.apply(this, arguments);
      }

      return On;

    })(Unary),
    Top: Top = (function(_super) {

      __extends(Top, _super);

      function Top() {
        return Top.__super__.constructor.apply(this, arguments);
      }

      return Top;

    })(Unary),
    Lock: Lock = (function(_super) {

      __extends(Lock, _super);

      function Lock() {
        return Lock.__super__.constructor.apply(this, arguments);
      }

      return Lock;

    })(Unary),
    Equality: Equality = (function(_super) {

      __extends(Equality, _super);

      function Equality(left, right) {
        this.left = left;
        this.right = right;
        Equality.__super__.constructor.call(this, this.left, this.right);
        this.operator = '==';
        this.operand1 = this.left;
        this.operand2 = this.right;
      }

      return Equality;

    })(Binary),
    In: In = (function(_super) {

      __extends(In, _super);

      function In() {
        return In.__super__.constructor.apply(this, arguments);
      }

      return In;

    })(Equality),
    With: With = (function(_super) {

      __extends(With, _super);

      function With(expr) {
        this.expr = expr;
        this.children = this.expr;
      }

      return With;

    })(Unary),
    WithRecursive: WithRecursive = (function(_super) {

      __extends(WithRecursive, _super);

      function WithRecursive() {
        return WithRecursive.__super__.constructor.apply(this, arguments);
      }

      return WithRecursive;

    })(With),
    Values: Values = (function(_super) {

      __extends(Values, _super);

      function Values(exprs, columns) {
        if (columns == null) {
          columns = [];
        }
        Values.__super__.constructor.call(this, exprs, columns);
      }

      Values.prototype.expressions = function(e) {
        if (e == null) {
          e = null;
        }
        if (e != null) {
          return this.left = e;
        } else {
          return this.left;
        }
      };

      Values.prototype.columns = function(c) {
        if (c == null) {
          c = null;
        }
        if (c != null) {
          return this.right = c;
        } else {
          return this.right;
        }
      };

      return Values;

    })(Binary),
    UnqualifiedColumn: UnqualifiedColumn = (function(_super) {

      __extends(UnqualifiedColumn, _super);

      function UnqualifiedColumn() {
        return UnqualifiedColumn.__super__.constructor.apply(this, arguments);
      }

      UnqualifiedColumn.prototype.attribute = function(attr) {
        if (attr != null) {
          return this.expr = attr;
        } else {
          return this.expr;
        }
      };

      UnqualifiedColumn.prototype.relation = function() {
        return this.expr.relation;
      };

      UnqualifiedColumn.prototype.column = function() {
        return this.expr.column;
      };

      UnqualifiedColumn.prototype.name = function() {
        return this.expr.name;
      };

      return UnqualifiedColumn;

    })(Unary)
  };

  exports = module.exports = Nodes;

}).call(this);
