// Generated by CoffeeScript 1.4.0
(function() {
  var Expressions, Predications, SqlLiteral, exports, u;

  u = require('underscore');

  Expressions = require('../expressions');

  Predications = require('../predications');

  SqlLiteral = (function() {

    function SqlLiteral(value) {
      this.value = value;
      u(this).extend(Expressions);
      u(this).extend(SqlLiteral);
    }

    SqlLiteral.prototype.toString = function() {
      return this.value;
    };

    return SqlLiteral;

  })();

  exports = module.exports = SqlLiteral;

}).call(this);
