// Generated by CoffeeScript 1.4.0
(function() {
  var Node, Unary, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Node = require('./node');

  Unary = (function(_super) {

    __extends(Unary, _super);

    function Unary(expr) {
      this.expr = expr;
      this.value = this.expr;
    }

    return Unary;

  })(Node);

  exports = module.exports = Unary;

}).call(this);
