// Generated by CoffeeScript 1.4.0
(function() {
  var Mysql, ToSql, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ToSql = require('./to-sql');

  Mysql = (function(_super) {

    __extends(Mysql, _super);

    function Mysql() {
      return Mysql.__super__.constructor.apply(this, arguments);
    }

    return Mysql;

  })(ToSql);

  exports = module.exports = Mysql;

}).call(this);
