// Generated by CoffeeScript 1.4.0
(function() {
  var Sqlite, ToSql, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ToSql = require('./to-sql');

  Sqlite = (function(_super) {

    __extends(Sqlite, _super);

    function Sqlite() {
      return Sqlite.__super__.constructor.apply(this, arguments);
    }

    return Sqlite;

  })(ToSql);

  exports = module.exports = Sqlite;

}).call(this);
